"""mas

Revision ID: ea57ea97186d
Revises: 30255519ffcb
Create Date: 2016-05-21 15:43:17.807826

"""

# revision identifiers, used by Alembic.
revision = 'ea57ea97186d'
down_revision = '30255519ffcb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.Unicode(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    ### end Alembic commands ###
